import { addMessages } from 'svelte-i18n';
import type { Dictionary } from './messages';

export const enDict: Dictionary = {
  'common.back': 'Back',
  'common.select': 'Select',
  'common.available_variants': 'Available variants',
  'common.loading': 'Loading...',
  'common.show_more': 'Show more',
  'common.sorting': 'Sorting',
  'common.sort_by': 'Sort by',
  'common.sort_direction': 'Sort direction',
  'common.ascending': 'Ascending',
  'common.descending': 'Descending',
  'common.grouping': 'Grouping',
  'fills.title': 'Fills',
  'fills.instrument_not_found': 'Fills for this instrument not found',
  'fills.return_to_fills': 'Return to positions list',
  'fills.shown_count': 'Shown {count, plural, one {# fill} other {# fills}} of {total}',
  'fills.position.fills_count': '{count, plural, =0 {no fills} one {# fill} other {# fills}}',
  'fills.options': 'Options',
  'fills.group_by_instrument_type': 'Group by asset type',
  'fills.sort_by.date': 'date',
  'fills.sort_by.pnl': 'profit or loss',
  'fills.sort_by.quantity': 'fills count',
  'instrument.groups.share': 'Shares',
  'instrument.groups.bond': 'Bonds',
  'instrument.groups.etf': 'ETFs',
  'instrument.groups.futures': 'Futures',
  'instrument.groups.currency': 'Currencies',
  'instrument.groups.other': 'Other',
  'portfolio.title': 'Portfolio',
  'settings.title': 'Settings',
  'settings.language': 'Language',
  'settings.select_language': 'Select language',
  'settings.common': 'Common',
  'settings.darkMode': 'Dark mode',
  'settings.security': 'Security',
  'settings.token': 'API token',
  'settings.enter_token': 'Enter API token',
  'settings.for_data_access_in': 'to get access for data in',
  'settings.in_settings': 'Settings',
  'settings.token_description':
    'To access for your orders data app uses token, witch can be created in your account settings',
  'settings.portfolio': 'Portfolio',
  'settings.account': 'Account',
  'settings.select_account': 'Select account',
};

addMessages('en-US', enDict);
